# Generated by Django 5.2.5 on 2025-08-23 17:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=20, unique=True)),
                ('home_location', models.CharField(max_length=100)),
                ('work_location', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('sim_swap', models.BooleanField(default=False)),
                ('sim_swap_date', models.DateField(blank=True, null=True)),
                ('imsi', models.CharField(max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=20, unique=True)),
                ('risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('normal_activity_start', models.TimeField(default='08:00:00')),
                ('normal_activity_end', models.TimeField(default='18:00:00')),
                ('incident', models.CharField(blank=True, default='none', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
