# Generated by Django 5.2.5 on 2025-08-23 17:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('PERSONAL', 'Personal Loan'), ('BUSINESS', 'Business Loan'), ('EMERGENCY', 'Emergency Loan')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_time', models.DateTimeField()),
                ('location_lat', models.FloatField()),
                ('location_long', models.FloatField()),
                ('device_imsi', models.CharField(max_length=20)),
                ('device_number', models.CharField(max_length=20)),
                ('risk_score', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('risk_profile', models.CharField(default='LOW', max_length=20)),
                ('flags', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('UNDER_REVIEW', 'Under Review')], default='PENDING', max_length=20)),
                ('approved', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='clients.client')),
            ],
        ),
    ]
